name: mosdef_dihedral_fit_docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10,<=3.11
  - vmd-python
  - ipython
  - numpydoc
  - mock
  - sphinx_rtd_theme
  - nbsphinx
  - sphinxcontrib
  - pycifrw
  - pytest
  - pytest-cov
  - mosdef-gomc>=1.3.0
  - pre-commit
  - sphinx=6.1.1
  - pip
  - pip:
      - bump2version
      - sphinxcontrib-svg2pdfconverter
      - sphinxcontrib-video
      - sphinxcontrib-serializinghtml
